; ============================================================
; AquaSense Pro Firmware
; PlatformIO Configuration
; ============================================================

[env:esp32dev]

; ESP32 platform
platform = espressif32

; ESP32 DevKit V1
board = esp32dev

; Arduino Framework
framework = arduino

; Serial Monitor baud rate
monitor_speed = 115200