; ============================================================
; AquaSense Pro Firmware
; ============================================================

[env:esp32dev]

; Platform
platform = espressif32

; Board
board = esp32dev

; Framework
framework = arduino

; Serial Monitor
monitor_speed = 115200

; External Libraries
lib_deps =
    bblanchon/ArduinoJson @ ^7.2.2

; Build Flags
build_flags =
    -DCORE_DEBUG_LEVEL=3